name: Auto Approve
on:
  push:
    branches:
      - main      

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'tyrobo'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"