name: Auto Merge from test
on:
  push:
    branches:
      - master
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: automerge
          branch: test
