name: Auto approve NO SENSE

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.1.0
      with:
        github-token: "${{ secrets.AUTO_MERGE }}"
