name: Auto PR from test
on:
  push:
    branches:
      - master
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: anything
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: automerge
          branch: master
  auto-approve:
    runs-on: ubuntu-latest
    needs: createPullRequest
    steps:
      - uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: "${{ secrets.AUTO_MERGE }}"
