name: Auto Merge from test
on:
  push:
    branches:
      - test
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin test:test
          git reset --hard test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: test
